spring:
  config:
    import:
      - aws-parameterstore:/config/test/
  cloud:
    aws:
      parameterstore:
        reload.strategy: REFRESH
    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: rabbitmq

test.local.data1: ${ssm.data1}


