server:
  port: 8081
  servlet:
    context-path: "/simulator"

spring:
  application:
    name: simulator
  cache:
    type: SIMPLE
  data:
    redis:
      host: redis
      repositories:
        enabled: false

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    health.show-details: always
    env.show-values: ALWAYS

logging:
  level:
    web: info
    sql: info 
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}]"

logback.access:
  enabled: true
