spring:
  data:
    redis:
      host: redis
  cloud:
    aws:
      endpoint: http://localstack:4566
      s3:
        path-style-access-enabled: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  metics.distribution.percentiles-histogram.http.server.requests: true
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans